apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:uSLLcIC7/FU=,iv:E2+vCMXXDuqt73JfFxbNHg+Lq3l0VqVvopxBSoLiHyY=,tag:dp/Sx5V2knGr5XFta1cB7g==,type:str]
    password: ENC[AES256_GCM,data:VSjLcqxHWeZNYFZeBJRizg==,iv:KjvrSqYF00WwQVS4DZIk3g9oMK8Mallr7nwQIzx6gTA=,tag:kW0xizbKvG2CTb78G26iHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-02-24T12:53:54Z'
    mac: ENC[AES256_GCM,data:eoElJGnqCoP4M/qGyIwo0tPYXC8k5K+WEzSFizGDI2DiFk70l2CMvzRX0I4TbDdRVm7Pvf9B5k2TcpA0SXxivZ85XADFOGRM0Zh/1AQL68IDMCRrMiGY4C0KbdEB33xzVcOye56qOmmQjVcH23INCL7TnSQvgbswyCZ2fxSJFyI=,iv:yPG69QMBKw4MnUMtKFIXW48MqNxKtqlZARSitCmbEW4=,tag:DVlh4Z59npzECw/DWgBccg==,type:str]
    pgp:
    -   created_at: '2020-02-24T12:53:52Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAyUpShfNkFB/AQgAM9vmp/XxpJiKAQP4TJ49NK2ulLK9hgbOJpCGmAiEUuOL
            R8TvoREIyiKdApV3l7OWJbry/6g6oTPD/mNNnB5TVfntDlOgl9AOccjn8wBnVQRD
            FXy2sROZT1GTp9aXf7ZIXrTMXw/qk4DCD3ojp/754GLSO/6is764M3hDRs0OCEay
            /QInG/K3OJk4moOfadtCoNPI3Wfjh2B9r9809/PJcknq2huIlWEOUWw5AIhyZmg2
            uwvXPO0rcdNIYHIY4rKAdI/2Unm71/Mf6RasWVAUXlg9TUNZWB0FZKu/3HQeaDi/
            5IRV4L0skWSQEkHhgT8z557EuVlxOw9dtB5wQ24VK9LgAeS1yS5YuJz2oCBTjHzU
            3XTM4drf4Dfg5+EsL+A04nIjKljg7eVIVcG3YHi9wyi2BQccATTvSxYTuOioMCRH
            vlexwjNqUODE5KTN41gCm03q2PMd0qZUUivivIWJFOGpLgA=
            =2PLL
            -----END PGP MESSAGE-----
        fp: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
