apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-revision-test-cm
data:
  revision: "<+kubernetes.release.revision>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-revision-test-deployment
  labels:
    app: kustomize-revision-test-nginx
spec:
  template:
    metadata:
      labels:
        revision: <+kubernetes.release.revision>
    spec:
      containers:
      - name: nginx
        env:
        - name: REVISION_NUMBER
          valueFrom:
            configMapKeyRef:
              name: kustomize-revision-test-cm
              key: "revision"
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command: [sh, -c, "[ $REVISION_NUMBER -eq <+kubernetes.release.revision> ] && exit 0 || exit 1"] # expect to fail without proper patch
          initialDelaySeconds: 1
          periodSeconds: 10
