apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-cm
data:
  revision: "{{.Values.revision}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}-nginx
    revision: "{{.Values.revision}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}-nginx
  template:
    metadata:
      labels:
        app: {{.Values.name}}-nginx
        revision: "{{.Values.revision}}"
    spec:
      containers:
      - name: nginx
        env:
        - name: REVISION_NUMBER
          valueFrom:
            configMapKeyRef:
              name: {{.Values.name}}-cm
              key: "revision"
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command: [sh, -c, "[ $REVISION_NUMBER -eq {{.Values.revision}} ] && exit 0 || exit 1"]
          initialDelaySeconds: 1
          periodSeconds: 10