{{- if .Values.pdb.minAvailable}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{.Values.name}}-pdb-statefulset
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{.Values.name}}
  {{- end}}