apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  selector:
    app: {{.Values.name}}
    type: front-end