{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
  {{.Values.env.config | toYaml | indent 2}}
---
{{- end}}

  {{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
  labels:
    release: {{.Release.Name}}
stringData:
  {{.Values.env.secrets | toYaml | indent 2}}
---
  {{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        release: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}
          {{- if or .Values.env.config .Values.env.secrets}}
          envFrom:
          {{- if .Values.env.config}}
          - configMapRef:
              name: {{.Values.name}}
          {{- end}}
          {{- if .Values.env.secrets}}
          - secretRef:
              name: {{.Values.name}}
          {{- end}}
          {{- end}}