apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-test-deployment
spec:
  selector:
    matchLabels:
      app: bg-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: bg-demo-app
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80