# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello
  
namePrefix: prod-

resources:
- deployment.yaml
- service.yaml

generators:
- cmGenerator.yaml
