resources:
  - ../../application
namePrefix: prod-
configMapGenerator:
- name: example-config
  namespace: example
  #behavior: replace
  files:
    - configs/config.json
patchesStrategicMerge:
  - env.yaml
