apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: example
spec:
  template :
    spec:
      containers:
        - name: example-app
          image: ${secrets.getValue("image")}
