apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
    name: http
  selector:
    app: {{.Values.name}}
