# https://theithollow.com/2019/02/04/kubernetes-endpoints/
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: {{.Values.name}}-endpoint
subsets:
  - addresses:
    - ip: "10.0.0.2" #The IP Address of the external web server
    ports:
    - port: 80
      name: "apache"