# K8S Deployments example
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: "true"
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}
    type: front-end
spec:
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
        type: front-end
    spec:
      imagePullSecrets:
        - name: {{.Values.name}}-dockercfg
      containers:
        - name: {{.Values.name}}-container
          image: {{.Values.image}}
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}