service: newcheckstry
frameworkVersion: '3.30.1'

provider:
  name: aws
  runtime: java8

# package:
#   artifact: <+artifact.path>  

functions:
  currentTime61:
    # handler: com.serverless.Handler
    name : ${opt:stage}-${self:custom.PARAMETERS.oem}
    image: <+artifact.image>
    events:
      - httpApi:
          path: /time
          method: get
  currentTime62:
    # handler: com.serverless.Handler
    image: <+artifact.image>
    events:
      - httpApi:
          path: /time1
          method: get   
custom:
  DEFAULT_ENV_SETUP: devint
  DEPLOYMENT_ENV: ${self:custom.CONFIG.ENV, self:custom.DEFAULT_ENV_SETUP}
  PARAMETERS: ${file(./env/${self:custom.DEPLOYMENT_ENV}/parameters.json)}           

plugins:
  - serverless-manifest-plugin
  
