version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-allu-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lmluvgpjp783"
s3_prefix = "sam-allu-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "afadc"
disable_rollback = true
image_repositories = []
