apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
spec:
    template:
      spec:
        containers:
        - name: example-app
          image: harness/todolist-sample:latest

