name: service-<+stage.variables.resourceNamePrefix>
image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

replicas: 1

createNamespace: true
namespace: <+infra.namespace>

labels:
  default: Default-Value
  serviceOverride1: OverrideIt
  serviceOverride2: OverrideIt
  serviceOverride3: OverrideIt
  environmentAllOverride1: OverrideIt
  environmentAllOverride2: OverrideIt
  environmentSpecificOverride1: OverrideIt
  environmentSpecificOverride2: OverrideIt
