{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: "true"
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
  {{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
        - name: {{.Values.name}}-dockercfg
      {{- end}}
      volumes:
        - name: foo
          secret:
            secretName: {{.Values.name}}
            defaultMode: 0755
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}
          volumeMounts:
            - name: foo
              mountPath: "/etc/foo"
          {{- if or .Values.env.config .Values.env.secrets}}
          envFrom:
          {{- if .Values.env.config}}
          - configMapRef:
              name: {{.Values.name}}-config
          {{- end}}
          {{- if .Values.env.secrets}}
          - secretRef:
              name: {{.Values.name}}-secret
          {{- end}}
          {{- end}}