{{- if .Values.pdb.minAvailable}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{.Values.name}}-pdb-custom
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{.Values.name}}-custom
  {{- end}}