# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: "true"
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg

---

apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
type: kubernetes.io/basic-auth
stringData:
  username: sneakyuser # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth