# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.name}}-persistentvolumeclaim
  namespace: {{.Values.namespace}}
spec:
  storageClassName: "manual" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: {{.Values.name}}-persistentvolume
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi