# https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{.Values.name}}-replicationcontroller
spec:
  replicas: 1
  selector:
    app: {{.Values.name}}
  template:
    metadata:
      name: nginx
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: {{.Values.name}}-container
          image: {{.Values.image}}
          ports:
            - containerPort: 80