{{- define "utility.service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.global.appName }}
{{- end }}